/**
 * Monthly report generator for IL BARBIERE OS — client-facing, PDF-oriented.
 *
 * Complements weekly-report.ts: same data source and visual identity, but cut
 * by month and written to be exported to PDF and sent to Santi & Fede.
 *
 * Two windows are reported side by side on purpose, because they answer
 * different questions and do NOT add up to the same totals:
 *   - Calendar month (1–31): the month as the calendar sees it.
 *   - Working weeks Tue–Sat (S1–S5): the month as the shop works it. The shop
 *     is closed Sun+Mon, so a week that ends on Sunday truncates Saturday and
 *     makes the last week look artificially weak.
 * Stating both, labelled, is deliberate — a reader who spots two different
 * totals with no explanation stops trusting every other number in the report.
 *
 * Charts are inline SVG, fonts are system fonts, and there is no JavaScript:
 * WeasyPrint renders no JS and fetches no network assets.
 *
 * Usage:
 *   bun scripts/monthly-report.ts                 # July 2026 (default)
 *   bun scripts/monthly-report.ts --month 2026-08
 *
 * Output: ~/Documents/Adriel-Core/02_BARBIERE-AS/informes-mensuales/
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import { isClosureRow } from '../src/shared/lib/closures';

const OUT_DIR = join(homedir(), 'Documents/Adriel-Core/02_BARBIERE-AS/informes-mensuales');
const MONTH_NAMES = [
  'enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio',
  'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre',
];
const DOW = ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'];
const DOW_SHORT = ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'];

type Row = {
  appointment_date: string;
  appointment_time: string | null;
  created_at: string;
  status: string;
  final_price: number | null;
  client_name: string | null;
  client_phone: string | null;
  qr_hash: string | null;
  barbers: { name: string } | null;
  services: { name: string } | null;
};

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 ? undefined : process.argv[i + 1];
}

function loadEnv(): Record<string, string> {
  const raw = readFileSync('.env.production.local', 'utf8');
  const env: Record<string, string> = {};
  for (const line of raw.split('\n')) {
    const t = line.trim();
    if (!t || t[0] === '#' || !t.includes('=')) continue;
    const i = t.indexOf('=');
    env[t.slice(0, i).trim()] = t.slice(i + 1).trim().replace(/^["']|["']$/g, '');
  }
  return env;
}

const env = loadEnv();

async function sbFetch(qs: string): Promise<any[]> {
  const url = `${env.NEXT_PUBLIC_SUPABASE_URL.replace(/\/$/, '')}/rest/v1/appointments?${qs}`;
  const res = await fetch(url, {
    headers: {
      apikey: env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
      Authorization: `Bearer ${env.NEXT_PUBLIC_SUPABASE_ANON_KEY}`,
    },
  });
  if (!res.ok) throw new Error(`Supabase ${res.status}: ${await res.text()}`);
  return res.json();
}

const money = (n: number) => '$' + Math.round(n).toLocaleString('es-AR');
const pct = (a: number, b: number) => (b ? Math.round((a / b) * 100) : 0);
const esc = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/**
 * Booking origin, derived from the qr_hash prefix — the schema has no `source`
 * column, so the prefix written at insert time is the only discriminator.
 *   MANUAL- -> loaded by a barber in the admin (appointmentService / CalendarView)
 *   VIP-    -> generated by the fixed-weekly VIP generator
 *   other   -> booked online by the client (booking/Confirmation.tsx)
 */
type Origin = 'interno' | 'vip' | 'externo' | 'sin-hash';
function origin(r: { qr_hash: string | null }): Origin {
  const h = r.qr_hash || '';
  if (h.startsWith('MANUAL-')) return 'interno';
  if (h.startsWith('VIP-')) return 'vip';
  return h ? 'externo' : 'sin-hash';
}

const isAttended = (r: Row) => r.status === 'attended';
const isOpen = (r: Row) => r.status === 'confirmed'; // never closed as attended or cancelled
const revenue = (rows: Row[]) => rows.filter(isAttended).reduce((s, r) => s + (r.final_price || 0), 0);
const dayLabel = (iso: string) => {
  const [y, m, d] = iso.split('-').map(Number);
  return `${DOW_SHORT[new Date(y, m - 1, d).getDay()]} ${d}/${m}`;
};

/** Tue–Sat working weeks that cover the month, including a Saturday spilling into the next. */
function workingWeeks(month: string): { tag: string; from: string; to: string }[] {
  const [y, m] = month.split('-').map(Number);
  const iso = (d: Date) =>
    `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
  const first = new Date(y, m - 1, 1);
  const last = new Date(y, m, 0);
  // Back up to the Tuesday of the week containing the 1st.
  const start = new Date(first);
  start.setDate(start.getDate() - ((start.getDay() + 5) % 7));
  const out: { tag: string; from: string; to: string }[] = [];
  let i = 1;
  for (let cur = new Date(start); cur <= last; cur.setDate(cur.getDate() + 7)) {
    const from = new Date(cur);
    const to = new Date(cur);
    to.setDate(to.getDate() + 4); // Tue + 4 = Sat
    out.push({ tag: `S${i++}`, from: iso(from), to: iso(to) });
  }
  return out;
}

// ---------------------------------------------------------------- SVG charts

/** Grouped bar chart: one bar per week, split attended / open / cancelled. */
function stackedBars(
  items: { label: string; parts: { value: number; color: string }[]; total: number }[],
  width = 640,
  height = 210
): string {
  const pad = { t: 14, r: 8, b: 34, l: 8 };
  const max = Math.max(...items.map((i) => i.total), 1);
  const bw = (width - pad.l - pad.r) / items.length;
  const barW = Math.min(bw * 0.56, 62);
  const plotH = height - pad.t - pad.b;
  let svg = '';
  items.forEach((it, idx) => {
    const cx = pad.l + bw * idx + bw / 2;
    let y = pad.t + plotH;
    it.parts.forEach((p) => {
      const h = (p.value / max) * plotH;
      y -= h;
      if (h > 0.4)
        svg += `<rect x="${(cx - barW / 2).toFixed(1)}" y="${y.toFixed(1)}" width="${barW.toFixed(1)}" height="${h.toFixed(1)}" fill="${p.color}" rx="2"/>`;
    });
    svg += `<text x="${cx.toFixed(1)}" y="${(pad.t + plotH - (it.total / max) * plotH - 5).toFixed(1)}" text-anchor="middle" font-size="11" font-weight="700" fill="#e8e8e8">${it.total}</text>`;
    svg += `<text x="${cx.toFixed(1)}" y="${(height - 14).toFixed(1)}" text-anchor="middle" font-size="10" fill="#8a8a8a">${esc(it.label)}</text>`;
  });
  svg += `<line x1="${pad.l}" y1="${pad.t + plotH}" x2="${width - pad.r}" y2="${pad.t + plotH}" stroke="#2a2a2a" stroke-width="1"/>`;
  return `<svg viewBox="0 0 ${width} ${height}" width="100%" preserveAspectRatio="xMidYMid meet">${svg}</svg>`;
}

/** Simple line-ish column chart for a money series. */
function moneyBars(items: { label: string; value: number }[], width = 640, height = 190): string {
  const pad = { t: 22, r: 8, b: 34, l: 8 };
  const max = Math.max(...items.map((i) => i.value), 1);
  const bw = (width - pad.l - pad.r) / items.length;
  const barW = Math.min(bw * 0.5, 54);
  const plotH = height - pad.t - pad.b;
  let svg = '';
  items.forEach((it, idx) => {
    const cx = pad.l + bw * idx + bw / 2;
    const h = (it.value / max) * plotH;
    const y = pad.t + plotH - h;
    svg += `<rect x="${(cx - barW / 2).toFixed(1)}" y="${y.toFixed(1)}" width="${barW.toFixed(1)}" height="${h.toFixed(1)}" fill="#00d4ff" opacity="0.75" rx="2"/>`;
    svg += `<text x="${cx.toFixed(1)}" y="${(y - 6).toFixed(1)}" text-anchor="middle" font-size="10" font-weight="700" fill="#e8e8e8">${money(it.value)}</text>`;
    svg += `<text x="${cx.toFixed(1)}" y="${(height - 14).toFixed(1)}" text-anchor="middle" font-size="10" fill="#8a8a8a">${esc(it.label)}</text>`;
  });
  svg += `<line x1="${pad.l}" y1="${pad.t + plotH}" x2="${width - pad.r}" y2="${pad.t + plotH}" stroke="#2a2a2a" stroke-width="1"/>`;
  return `<svg viewBox="0 0 ${width} ${height}" width="100%" preserveAspectRatio="xMidYMid meet">${svg}</svg>`;
}

/** Same shape as moneyBars, but labels the bars with plain counts. */
function countBars(items: { label: string; value: number }[], highlight: number, width = 640, height = 190): string {
  const pad = { t: 22, r: 8, b: 34, l: 8 };
  const max = Math.max(...items.map((i) => i.value), 1);
  const bw = (width - pad.l - pad.r) / items.length;
  const barW = Math.min(bw * 0.5, 54);
  const plotH = height - pad.t - pad.b;
  let svg = '';
  items.forEach((it, idx) => {
    const cx = pad.l + bw * idx + bw / 2;
    const h = (it.value / max) * plotH;
    const y = pad.t + plotH - h;
    const on = idx === highlight;
    svg += `<rect x="${(cx - barW / 2).toFixed(1)}" y="${y.toFixed(1)}" width="${barW.toFixed(1)}" height="${h.toFixed(1)}" fill="${on ? '#00d4ff' : '#3b3b45'}" rx="2"/>`;
    svg += `<text x="${cx.toFixed(1)}" y="${(y - 6).toFixed(1)}" text-anchor="middle" font-size="11" font-weight="700" fill="${on ? '#00d4ff' : '#9a9aa2'}">${it.value}</text>`;
    svg += `<text x="${cx.toFixed(1)}" y="${(height - 14).toFixed(1)}" text-anchor="middle" font-size="10" fill="${on ? '#e8e8e8' : '#8a8a92'}">${esc(it.label)}</text>`;
  });
  svg += `<line x1="${pad.l}" y1="${pad.t + plotH}" x2="${width - pad.r}" y2="${pad.t + plotH}" stroke="#2a2a2a" stroke-width="1"/>`;
  return `<svg viewBox="0 0 ${width} ${height}" width="100%" preserveAspectRatio="xMidYMid meet">${svg}</svg>`;
}

/**
 * Horizontal 100% stacked bar for the origin split.
 *
 * Laid out in real user units with a uniform aspect ratio, NOT in percent with
 * preserveAspectRatio="none": a non-uniformly scaled viewBox stretches the
 * labels along with the rects and the percentages collide into each other.
 */
function splitBar(parts: { label: string; value: number; color: string }[], total: number): string {
  const W = 640, H = 34;
  let x = 0;
  let svg = '';
  for (const p of parts) {
    const w = (p.value / total) * W;
    if (w <= 0) continue;
    svg += `<rect x="${x.toFixed(1)}" y="0" width="${w.toFixed(1)}" height="${H}" fill="${p.color}"/>`;
    if (w > 42)
      svg += `<text x="${(x + w / 2).toFixed(1)}" y="22" text-anchor="middle" font-size="14" font-weight="700" fill="#07141a">${Math.round((p.value / total) * 100)}%</text>`;
    x += w;
  }
  return `<svg viewBox="0 0 ${W} ${H}" width="100%" preserveAspectRatio="xMidYMid meet">${svg}</svg>`;
}

// ------------------------------------------------------------------- report

async function main() {
  const MONTH = arg('month') || '2026-07';
  const [Y, M] = MONTH.split('-').map(Number);
  const monthLabel = `${MONTH_NAMES[M - 1]} ${Y}`;

  const select =
    'select=appointment_date,appointment_time,created_at,status,final_price,client_name,client_phone,qr_hash,barbers(name),services(name)';
  const all: Row[] = await sbFetch(`${select}&order=appointment_date.asc&limit=20000`);
  // Shop closures are booked as ordinary appointments; they are not turnos.
  const live = all.filter((r) => !isClosureRow(r));

  // --- calendar month
  const mo = live.filter((r) => r.appointment_date?.startsWith(MONTH));
  const closures = all.filter((r) => r.appointment_date?.startsWith(MONTH)).length - mo.length;
  const att = mo.filter(isAttended);
  const open = mo.filter(isOpen);
  const cancelled = mo.filter((r) => r.status === 'cancelled');
  const fact = revenue(mo);
  const ticket = att.length ? fact / att.length : 0;
  const openMoney = open.reduce((s, r) => s + (r.final_price || 0), 0);
  const clients = new Set(mo.map((r) => (r.client_phone || '').trim()).filter(Boolean)).size;

  // --- origin split
  const byOrigin: Record<Origin, Row[]> = { interno: [], vip: [], externo: [], 'sin-hash': [] };
  for (const r of mo) byOrigin[origin(r)].push(r);

  // --- working weeks
  const weeks = workingWeeks(MONTH).map((w) => {
    const rows = live.filter((r) => r.appointment_date >= w.from && r.appointment_date <= w.to);
    const days = new Set(rows.map((r) => r.appointment_date)).size || 1;
    const a = rows.filter(isAttended);
    const o = rows.filter(isOpen);
    return {
      ...w,
      rows,
      days,
      att: a.length,
      open: o.length,
      cancelled: rows.filter((r) => r.status === 'cancelled').length,
      total: rows.length,
      fact: revenue(rows),
      openMoney: o.reduce((s, r) => s + (r.final_price || 0), 0),
      ext: rows.filter((r) => origin(r) === 'externo').length,
    };
  });

  // --- unclosed days, worst first
  // Scoped to the CALENDAR month on purpose: the "sin cerrar" KPI above counts
  // the calendar month, and a headline that disagreed with it by a few turnos
  // (the working weeks reach into the next month) would read as a mistake.
  const openByDay: Record<string, Row[]> = {};
  for (const r of open) {
    (openByDay[r.appointment_date] = openByDay[r.appointment_date] || []).push(r);
  }
  const worstDays = Object.entries(openByDay)
    .map(([d, rows]) => {
      const dayRows = live.filter((r) => r.appointment_date === d);
      return {
        date: d,
        open: rows.length,
        total: dayRows.length,
        money: rows.reduce((s, r) => s + (r.final_price || 0), 0),
      };
    })
    .sort((a, b) => b.open - a.open);
  const openTotal = worstDays.reduce((s, d) => s + d.open, 0);
  const openTotalMoney = worstDays.reduce((s, d) => s + d.money, 0);

  // --- Saturdays
  const saturdays = [...new Set(live.map((r) => r.appointment_date))]
    .filter((d) => d >= weeks[0].from && d <= weeks[weeks.length - 1].to)
    .filter((d) => {
      const [y, m, dd] = d.split('-').map(Number);
      return new Date(y, m - 1, dd).getDay() === 6;
    })
    .sort()
    .map((d) => {
      const rows = live.filter((r) => r.appointment_date === d);
      return {
        date: d,
        total: rows.length,
        att: rows.filter(isAttended).length,
        open: rows.filter(isOpen).length,
        fact: revenue(rows),
      };
    });

  // --- online bookings by weekday of creation (app usage by clients)
  const extByDow = Array(7).fill(0);
  let extTotal = 0;
  for (const r of live) {
    if (origin(r) !== 'externo' || !r.created_at) continue;
    const d = new Date(r.created_at).toLocaleDateString('en-CA', { timeZone: 'America/Argentina/Buenos_Aires' });
    const [y, m, dd] = d.split('-').map(Number);
    extByDow[new Date(y, m - 1, dd).getDay()]++;
    extTotal++;
  }
  const bestDow = extByDow.indexOf(Math.max(...extByDow));

  // --- barbers
  const barbers = Object.entries(
    mo.reduce<Record<string, Row[]>>((acc, r) => {
      const n = r.barbers?.name || 'Sin asignar';
      (acc[n] = acc[n] || []).push(r);
      return acc;
    }, {})
  )
    .map(([name, rows]) => ({
      name,
      total: rows.length,
      att: rows.filter(isAttended).length,
      open: rows.filter(isOpen).length,
      fact: revenue(rows),
      ext: rows.filter((r) => origin(r) === 'externo').length,
    }))
    .sort((a, b) => b.fact - a.fact);

  const cancelByOrigin = (['externo', 'interno', 'vip'] as Origin[]).map((o) => {
    const rows = byOrigin[o];
    const c = rows.filter((r) => r.status === 'cancelled').length;
    return { origin: o, total: rows.length, cancelled: c, rate: rows.length ? (c / rows.length) * 100 : 0 };
  });

  const now = new Date();
  const stamp = `${now.getDate()}/${now.getMonth() + 1}/${now.getFullYear()}`;

  const html = render({
    monthLabel, mo, closures, att, open, cancelled, fact, ticket, openMoney, clients,
    byOrigin, weeks, worstDays, openTotal, openTotalMoney, saturdays, extByDow, extTotal,
    bestDow, barbers, cancelByOrigin, stamp,
  });

  mkdirSync(OUT_DIR, { recursive: true });
  const out = join(OUT_DIR, `il-barbiere-mensual-${MONTH}.html`);
  writeFileSync(out, html);
  console.log(`OK — ${monthLabel}: ${mo.length} turnos, ${money(fact)}, ${openTotal} sin cerrar`);
  console.log(`  → ${out}`);
}

function render(d: any): string {
  const CY = '#00d4ff', PU = '#a855f7', PK = '#ec4899', GR = '#22c55e', WA = '#f59e0b', DA = '#ef4444';

  const kpi = (label: string, val: string, sub: string, color: string) =>
    `<div class="kpi"><div class="kl">${label}</div><div class="kv" style="color:${color}">${val}</div><div class="ks">${sub}</div></div>`;

  const weekRows = d.weeks
    .map(
      (w: any) => `<tr>
      <td><b>${w.tag}</b><span class="dim"> ${dayLabel(w.from)}–${dayLabel(w.to)}</span></td>
      <td class="n">${w.total}</td>
      <td class="n">${w.att}</td>
      <td class="n">${money(w.fact)}</td>
      <td class="n">${money(w.fact / w.days)}</td>
      <td class="n ${w.open >= 15 ? 'bad' : w.open >= 8 ? 'warn' : ''}">${w.open}</td>
    </tr>`
    )
    .join('');

  const satRows = d.saturdays
    .map(
      (s: any) => `<tr>
      <td>${dayLabel(s.date)}</td>
      <td class="n">${s.total}</td>
      <td class="n">${s.att}</td>
      <td class="n">${money(s.fact)}</td>
      <td class="n ${s.open >= 8 ? 'bad' : s.open >= 4 ? 'warn' : ''}">${s.open}</td>
    </tr>`
    )
    .join('');

  const worstRows = d.worstDays
    .slice(0, 8)
    .map(
      (x: any) => `<tr>
      <td>${DOW[new Date(x.date + 'T12:00:00').getDay()]} ${x.date.slice(8, 10)}/${x.date.slice(5, 7)}</td>
      <td class="n">${x.total}</td>
      <td class="n bad">${x.open}</td>
      <td class="n">${money(x.money)}</td>
    </tr>`
    )
    .join('');

  const barberCards = d.barbers
    .map(
      (b: any) => `<div class="card barber">
      <h3>${esc(b.name)}</h3>
      <div class="row"><span>Turnos del mes</span><b>${b.total}</b></div>
      <div class="row"><span>Atendidos</span><b>${b.att}</b></div>
      <div class="row"><span>Facturación</span><b>${money(b.fact)}</b></div>
      <div class="row"><span>Ticket promedio</span><b>${money(b.att ? b.fact / b.att : 0)}</b></div>
      <div class="row"><span>Reservas online recibidas</span><b>${b.ext}</b></div>
      <div class="row"><span>Turnos sin cerrar</span><b class="${b.open >= 25 ? 'bad' : 'warn'}">${b.open}</b></div>
    </div>`
    )
    .join('');

  const cancelRows = d.cancelByOrigin
    .map((c: any) => {
      const name = c.origin === 'externo' ? 'Reserva online del cliente' : c.origin === 'interno' ? 'Cargado por ustedes' : 'Fijo semanal (VIP)';
      return `<tr><td>${name}</td><td class="n">${c.total}</td><td class="n">${c.cancelled}</td>
      <td class="n ${c.rate > 18 ? 'bad' : ''}">${c.rate.toFixed(1)}%</td></tr>`;
    })
    .join('');

  const weekChart = stackedBars(
    d.weeks.map((w: any) => ({
      label: w.tag,
      total: w.total,
      parts: [
        { value: w.att, color: CY },
        { value: w.open, color: WA },
        { value: w.cancelled, color: '#3a3a3a' },
      ],
    }))
  );
  const moneyChart = moneyBars(d.weeks.map((w: any) => ({ label: w.tag, value: w.fact })));
  const originSplit = splitBar(
    [
      { label: 'interno', value: d.byOrigin.interno.length, color: PU },
      { label: 'externo', value: d.byOrigin.externo.length, color: CY },
      { label: 'vip', value: d.byOrigin.vip.length, color: PK },
    ],
    d.mo.length
  );

  const dowOrder = [1, 2, 3, 4, 5, 6, 0];
  const dowChart = countBars(
    dowOrder.map((i) => ({ label: DOW_SHORT[i], value: d.extByDow[i] })),
    dowOrder.indexOf(d.bestDow)
  );

  const extPct = pct(d.byOrigin.externo.length, d.mo.length);
  const intPct = pct(d.byOrigin.interno.length, d.mo.length);
  const vipPct = pct(d.byOrigin.vip.length, d.mo.length);
  const dowPct = pct(d.extByDow[d.bestDow], d.extTotal);

  return `<meta charset="utf-8"><title>IL BARBIERE OS — Informe mensual ${d.monthLabel}</title>
<style>
@page { size: A4; margin: 12mm 11mm; background: #0b0b0d; }
* { margin:0; padding:0; box-sizing:border-box; }
body { font-family:'DejaVu Sans','Liberation Sans',sans-serif; background:#0b0b0d; color:#e2e2e4; font-size:10.5px; line-height:1.5; }
h1 { font-size:23px; letter-spacing:1.5px; text-transform:uppercase; color:#00d4ff; font-weight:700; }
h2 { font-size:13px; text-transform:uppercase; letter-spacing:1.2px; color:#00d4ff; margin:0 0 3px; font-weight:700; }
h3 { font-size:12.5px; letter-spacing:.6px; color:#a855f7; margin-bottom:7px; font-weight:700; }
p { margin:0 0 7px; }
.hdr { border-bottom:2px solid #00d4ff; padding-bottom:11px; margin-bottom:13px; }
.hdr .sub { color:#9a9aa2; font-size:11px; margin-top:4px; }
.hdr .meta { color:#6f6f78; font-size:9.5px; margin-top:6px; }
/* Sections flow across pages so the PDF fills its pages; headings and leads are
   glued to what follows so nothing is left orphaned at the foot of a page. */
.sec { margin:15px 0 0; }
h2, h3, .sec > .lead { page-break-after:avoid; break-after:avoid; }
.sec > .lead { color:#9a9aa2; margin:4px 0 9px; }
.card { background:#141418; border:1px solid #26262c; border-radius:8px; padding:11px 13px; page-break-inside:avoid; }
.kpis { display:flex; gap:7px; margin-bottom:5px; }
.kpi { flex:1; background:#141418; border:1px solid #26262c; border-top:2px solid #00d4ff; border-radius:7px; padding:9px 10px; }
.kl { color:#8a8a92; font-size:8px; letter-spacing:.8px; text-transform:uppercase; }
.kv { font-size:19px; font-weight:700; margin:3px 0 1px; line-height:1.15; }
.ks { color:#82828c; font-size:8.5px; }
table { width:100%; border-collapse:collapse; font-size:10px; }
th { text-align:left; color:#8a8a92; font-size:8px; letter-spacing:.7px; text-transform:uppercase; padding:6px 7px; border-bottom:1px solid #33333a; font-weight:700; }
td { padding:5.5px 7px; border-bottom:1px solid #202026; }
td.n { text-align:right; font-variant-numeric:tabular-nums; }
tr:last-child td { border-bottom:none; }
.dim { color:#75757e; font-weight:400; }
.bad { color:#ef4444; font-weight:700; }
.warn { color:#f59e0b; font-weight:700; }
.ok { color:#22c55e; font-weight:700; }
.two { display:flex; gap:9px; }
.two > * { flex:1; }
.legend { display:flex; gap:13px; color:#8a8a92; font-size:9px; margin-top:5px; }
.legend i { display:inline-block; width:9px; height:9px; border-radius:2px; margin-right:4px; vertical-align:-1px; }
.alert { background:#1d1410; border:1px solid #f59e0b; border-left:4px solid #f59e0b; border-radius:8px; padding:12px 14px; page-break-inside:avoid; }
.alert h2 { color:#f59e0b; }
.ask { background:#101820; border:1px solid #00d4ff; border-radius:8px; padding:12px 14px; margin-top:10px; page-break-inside:avoid; }
.ask h3 { color:#00d4ff; }
.ask ol { margin:6px 0 0 17px; }
.ask li { margin-bottom:5px; }
.barber .row { display:flex; justify-content:space-between; padding:3.5px 0; border-bottom:1px solid #202026; }
.barber .row span { color:#8a8a92; }
.barber .row:last-child { border-bottom:none; }
.note { color:#75757e; font-size:9px; font-style:italic; margin-top:6px; }
.foot { margin-top:18px; padding-top:11px; border-top:1px solid #33333a; text-align:center; color:#75757e; font-size:9px; }
.foot b { color:#00d4ff; }
.pb { page-break-before:always; }
ul.next { margin:5px 0 0 16px; }
ul.next li { margin-bottom:4px; }
</style>

<div class="hdr">
  <h1>Il Barbiere OS</h1>
  <div class="sub">Informe mensual · <b>${d.monthLabel}</b> — para Santi &amp; Fede</div>
  <div class="meta">Generado el ${d.stamp} por Soluciones Adriel-IA · datos tomados en vivo del sistema</div>
</div>

<div class="sec">
  <h2>Por qué les mandamos esto</h2>
  <p class="lead">Todos los meses miramos los datos de la app de punta a punta: no sólo cuánto se facturó, sino
  cómo se usa el sistema, de dónde entran los turnos y dónde se pierde información. La idea es que Il Barbiere OS
  sea cada vez <b>más independiente</b> — que trabaje solo, sin que ustedes tengan que estar encima — y
  <b>escalable</b>, que aguante crecer sin romperse. Este informe es lo que encontramos en ${d.monthLabel}, y
  cierra con una pregunta concreta para ustedes.</p>
</div>

<div class="sec">
  <h2>El mes en números</h2>
  <div class="kpis">
    ${kpi('Turnos', String(d.mo.length), `${d.closures} cierres de local excluidos`, CY)}
    ${kpi('Atendidos', String(d.att.length), `${pct(d.att.length, d.mo.length)}% de los turnos`, GR)}
    ${kpi('Facturación', money(d.fact), 'turnos cerrados como atendidos', GR)}
  </div>
  <div class="kpis">
    ${kpi('Ticket promedio', money(d.ticket), 'por turno atendido', PU)}
    ${kpi('Clientes distintos', String(d.clients), 'por teléfono, en el mes', PU)}
    ${kpi('Sin cerrar', String(d.open.length), `${money(d.openMoney)} sin registrar`, WA)}
  </div>
  <p class="note">Facturación cuenta sólo turnos marcados como atendidos. Los turnos sin cerrar (abajo) no están
  sumados en ningún lado — por eso el número real del mes es, como mínimo, el que ven acá.</p>
</div>

<div class="sec">
  <h2>Semana a semana</h2>
  <p class="lead">Medimos por semana laboral <b>martes a sábado</b>, no por semana de calendario. La barbería
  cierra domingo y lunes: si cortáramos el domingo, el sábado quedaría partido al medio y la última semana
  parecería floja sin serlo.</p>
  <div class="card">
    ${weekChart}
    <div class="legend">
      <span><i style="background:${CY}"></i>Atendidos</span>
      <span><i style="background:${WA}"></i>Sin cerrar</span>
      <span><i style="background:#3a3a3a"></i>Cancelados</span>
    </div>
  </div>
  <div class="card" style="margin-top:9px">
    <h3>Facturación por semana</h3>
    ${moneyChart}
  </div>
  <div class="card" style="margin-top:9px">
    <table>
      <thead><tr><th>Semana</th><th class="n">Turnos</th><th class="n">Atend.</th><th class="n">Facturado</th><th class="n">Por día</th><th class="n">Sin cerrar</th></tr></thead>
      <tbody>${weekRows}</tbody>
    </table>
  </div>
</div>

<div class="sec">
  <h2>De dónde vienen los turnos</h2>
  <p class="lead">Podemos distinguir cada turno según cómo entró al sistema. En ${d.monthLabel} quedó así:</p>
  <div class="card">
    ${originSplit}
    <div class="legend">
      <span><i style="background:${PU}"></i>Cargado por ustedes — ${d.byOrigin.interno.length} (${intPct}%)</span>
      <span><i style="background:${CY}"></i>Reservado online por el cliente — ${d.byOrigin.externo.length} (${extPct}%)</span>
      <span><i style="background:${PK}"></i>Fijo semanal automático — ${d.byOrigin.vip.length} (${vipPct}%)</span>
    </div>
  </div>
  <p style="margin-top:9px">Hoy <b>${intPct + vipPct}% de los turnos entra desde adentro</b> y ${extPct}% lo reserva
  el cliente solo. Es lo esperable en un sistema joven: la app todavía acompaña al mostrador más de lo que lo
  reemplaza. Ese número subiendo mes a mes es, para nosotros, la señal de que el sistema se vuelve independiente.</p>
</div>

<div class="sec">
  <h2>El hallazgo del mes: el ${DOW[d.bestDow].toLowerCase()}</h2>
  <div class="card">
    <h3>Reservas online según el día en que el cliente las hace</h3>
    ${dowChart}
  </div>
  <p style="margin-top:9px"><b>${dowPct}% de las reservas online se hacen el ${DOW[d.bestDow].toLowerCase()}</b>
  (${d.extByDow[d.bestDow]} de ${d.extTotal}) — justo el día que la barbería está <b>cerrada</b>.</p>
  <p>Esto es lo más valioso que encontramos, y conviene decirlo claro: <b>esos turnos no existirían sin la app</b>.
  Son clientes que deciden cortarse el pelo cuando no hay nadie para atenderles el teléfono. La app no les está
  sacando trabajo del mostrador: les está agregando trabajo que antes se perdía.</p>
</div>

<div class="sec">
  <h2>Cada uno</h2>
  <div class="two">${barberCards}</div>
</div>

<div class="sec">
  <h2>Cancelaciones</h2>
  <div class="card">
    <table>
      <thead><tr><th>Origen del turno</th><th class="n">Turnos</th><th class="n">Cancelados</th><th class="n">% cancelación</th></tr></thead>
      <tbody>${cancelRows}</tbody>
    </table>
  </div>
  <p style="margin-top:8px">El turno que reserva el cliente online se cancela <b>más del doble</b> que el que cargan
  ustedes. Tiene lógica: reservar desde el celular no cuesta nada, y cancelar tampoco. Es el costo de la comodidad,
  y se corrige — acá abajo está cómo.</p>
</div>

<div class="sec">
  <h2>En qué estamos trabajando</h2>
  <p class="lead">Lo que encontramos este mes nos ordenó la lista. Esto es lo que viene, y por qué:</p>
  <div class="card">
    <ul class="next">
      <li><b>Cierre de día automático</b> — que al final de la jornada el sistema les pregunte por los turnos que
      quedaron abiertos, en vez de esperar que se acuerden. Ataca directo los ${d.openTotal} turnos sin cerrar.</li>
      <li><b>Confirmación por WhatsApp</b> — recordatorio automático al cliente antes del turno. Es la palanca más
      directa contra el ${d.cancelByOrigin[0].rate.toFixed(0)}% de cancelación de las reservas online.</li>
      <li><b>Seña con Mercado Pago</b> — reservar online con algo de compromiso adelante. El que pone plata, viene.</li>
      <li><b>Aviso cuando un cliente cancela</b> — que se enteren en el momento y puedan reponer el hueco.</li>
    </ul>
  </div>
  <p style="margin-top:8px">El objetivo de fondo es siempre el mismo: que el sistema haga solo todo lo que hoy
  depende de que alguien se acuerde. Cada cosa que la app resuelve sin ustedes es tiempo que vuelve a la silla.</p>
</div>

<div class="alert pb">
  <h2>⚠ Lo que necesitamos preguntarles: ${d.openTotal} turnos sin cerrar</h2>
  <p style="margin-top:6px">En ${d.monthLabel} quedaron <b>${d.openTotal} turnos en estado "confirmado"</b> que
  nunca se marcaron ni como atendidos ni como cancelados. En plata son <b>${money(d.openTotalMoney)}</b> que el
  sistema no tiene registrados.</p>
  <p><b>No sabemos qué pasó con esos turnos, y no queremos suponerlo.</b> Puede ser que el cliente vino y se cobró
  igual pero no se marcó en la app; puede ser que no vino y quedó ahí; puede ser que la pantalla no les esté
  quedando cómoda para cerrarlos. Cada una de esas causas se arregla distinto, y sólo ustedes saben cuál es.</p>

  <div class="card" style="margin-top:10px">
    <h3>Los días donde más se acumuló</h3>
    <table>
      <thead><tr><th>Día</th><th class="n">Turnos del día</th><th class="n">Sin cerrar</th><th class="n">Plata sin registrar</th></tr></thead>
      <tbody>${worstRows}</tbody>
    </table>
  </div>

  <div class="card" style="margin-top:9px">
    <h3>El patrón: los sábados</h3>
    <table>
      <thead><tr><th>Sábado</th><th class="n">Turnos</th><th class="n">Atendidos</th><th class="n">Facturado</th><th class="n">Sin cerrar</th></tr></thead>
      <tbody>${satRows}</tbody>
    </table>
    <p class="note">Los martes y jueves cierran casi perfecto. Los sábados no. Nuestra sospecha: se termina tarde,
    se van, el lunes está cerrado y el martes ya arrancó otra semana. Pero es una sospecha nuestra, no un dato.
    El último sábado de la tabla ya cae en el mes siguiente: va incluido porque es el que cierra la última semana
    laboral, y por eso no está sumado en los totales del mes.</p>
  </div>

  <div class="ask">
    <h3>Las tres preguntas</h3>
    <ol>
      <li><b>¿Esos turnos se cobraron?</b> Si la plata entró y sólo faltó marcarlo, el mes cerró mejor de lo que
      dice este informe y lo corregimos.</li>
      <li><b>¿Qué pasa puntualmente los sábados?</b> Si es cuestión de tiempo al cierre, la app tiene que
      resolverlo sola, no ustedes.</li>
      <li><b>¿Cerrar un turno les resulta incómodo desde el celular?</b> Si son muchos toques, es un problema
      nuestro y lo rediseñamos.</li>
    </ol>
    <p style="margin-top:7px">Con que nos contesten esto por WhatsApp alcanza. No hace falta que revisen nada.</p>
  </div>
</div>

<div class="foot">
  <b>Soluciones Adriel-IA</b> · Consultoría de IA para PyMEs<br>
  Informe generado automáticamente desde los datos del sistema · ${d.stamp}
</div>`;
}

main().catch((e) => {
  console.error('ERR', e.message);
  process.exit(1);
});
